### ISSUE TITLE
Subscribe/Unsubscribe checkbox from individual user profile does not reflect the configuration

### ISSUE THREAD

**Issue by reachmazharul** [weMail/Subscribe2#3]
On the registered user's settings ( **Subscribe2->Settings->Registerd Users** ) there is an option called "**Show one-click subscription on profile page:**" which allows show and hie the **Subscribe/Unsubscribe** checkbox on the individual user profile. 

By default, it behaves as enable. But if the checkbox is marked as unchecked then it's not possible to mark it as checked the next time. 

How to Reproduce the Issue:
https://www.loom.com/share/d3f9c287084f492abdff9e6475276471

Environment details:
WordPress: Version 5.6.1
Subscribe2: Version 10.34

**Comment by bdmehedi** [comment]
Fixed the issue
